# Generated by Django 5.0.4 on 2024-04-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_storage', '0002_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='link',
            name='slug',
        ),
    ]
